/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pelanggan;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import pelanggan.koneksi;

/**
 *
 * @author DELL
 */
public class framePelanggan extends javax.swing.JFrame {

    // Mengkoneksikan database ke netbeans    
    private Connection connect = new koneksi().conn();
    private DefaultTableModel tabmode;
    
    /**
     * Creates new form framePelanggan
     */
    public framePelanggan() {
        initComponents();
        aktif();
        kosong();
        datatable();
    }
    
    protected void aktif() { // membuat saat pertama kali dijalankan maka kursor akan ada di txt_id_pelanggan
        txt_nama_pelanggan.requestFocus();
    }
    
    protected void kosong() { //untuk mengosongkan tiap-tiap teks field
        
        txt_nama_pelanggan.setText("");
        txt_notelp_pelanggan.setText("");
        txt_alamat_pelanggan.setText("");
        txt_cari.setText("");
        buttonGroup1.clearSelection();
    }
    
    protected void datatable() {
        Object[] Baris = {"ID Pelanggan", "Nama", "Jenis Kelamin", "Nomor Telepon", "Alamat"}; //nama kolom tabel di form
        tabmode = new DefaultTableModel(null, Baris);
        
        String cariItem = txt_cari.getText();
        
        try {
            String sql = "SELECT * FROM pelanggan WHERE id_pelanggan LIKE '%" + cariItem + "%' OR nama_pelanggan LIKE '%" + cariItem + "%' ORDER BY id_pelanggan ASC";
            Statement stat = connect.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                tabmode.addRow(new Object[] {
                   hasil.getString("id_pelanggan"),
                   hasil.getString(2),
                   hasil.getString(3),
                   hasil.getString(4),
                   hasil.getString(5)
                });
            }
            tbl_pelanggan.setModel(tabmode);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Dipanggil" + e);
        }
    }
    
    protected void datatableriwayat(String a) {
        Object[] Baris = {"ID Transaksi", "Tanggal Transaksi", "Barang", "Jumlah", "Harga"}; //nama kolom tabel di form
        tabmode = new DefaultTableModel(null, Baris);
         
        try {
            String sql = "SELECT transaksi.id_transaksi, transaksi.tanggal_transaksi, manajemen.nama_barang, transaksi_item.jumlah, transaksi_item.harga "
                    + "FROM manajemen "
                    + "JOIN transaksi_item ON manajemen.id_barang = transaksi_item.id_barang "
                    + "JOIN transaksi ON transaksi.id_transaksi = transaksi_item.id_transaksi "
                    + "WHERE transaksi.id_pelanggan = ? "
                    + "ORDER BY transaksi.id_transaksi ASC";
            PreparedStatement stat = connect.prepareStatement(sql);
            stat.setString(1, a);
            ResultSet hasil = stat.executeQuery();
            while (hasil.next()) {
                tabmode.addRow(new Object[] {
                   hasil.getString("id_transaksi"),
                   hasil.getString("tanggal_transaksi"),
                   hasil.getString("nama_barang"),
                   hasil.getString("jumlah"),
                   hasil.getString("harga")
                });
            }
            tbl_transaksiPelanggan.setModel(tabmode);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Dipanggil" + e);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbl_dataPelanggan = new javax.swing.JLabel();
        lbl_nama_pelanggan = new javax.swing.JLabel();
        lbl_jk_pelanggan = new javax.swing.JLabel();
        lbl_noTelp_pelanggan = new javax.swing.JLabel();
        lbl_alamat_pelanggan = new javax.swing.JLabel();
        txt_nama_pelanggan = new javax.swing.JTextField();
        txt_alamat_pelanggan = new javax.swing.JTextField();
        jk_laki = new javax.swing.JRadioButton();
        jk_perempuan = new javax.swing.JRadioButton();
        txt_notelp_pelanggan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pelanggan = new javax.swing.JTable();
        buttonBatal = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        buttonUbah = new javax.swing.JButton();
        buttonSimpan = new javax.swing.JButton();
        buttonCari = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_transaksiPelanggan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_dataPelanggan.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        lbl_dataPelanggan.setText("DATA PELANGGAN");

        lbl_nama_pelanggan.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbl_nama_pelanggan.setText("Nama");

        lbl_jk_pelanggan.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbl_jk_pelanggan.setText("Jenis Kelamin");

        lbl_noTelp_pelanggan.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbl_noTelp_pelanggan.setText("Nomor Telepon");

        lbl_alamat_pelanggan.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        lbl_alamat_pelanggan.setText("Alamat");

        buttonGroup1.add(jk_laki);
        jk_laki.setText("Laki-laki");

        buttonGroup1.add(jk_perempuan);
        jk_perempuan.setText("Perempuan");

        tbl_pelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Pelanggan", "Nama", "Jenis Kelamin", "Nomor Telepon", "Alamat"
            }
        ));
        tbl_pelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pelangganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_pelanggan);

        buttonBatal.setText("Batal");
        buttonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBatalActionPerformed(evt);
            }
        });

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        buttonUbah.setText("Ubah");
        buttonUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUbahActionPerformed(evt);
            }
        });

        buttonSimpan.setText("Simpan");
        buttonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSimpanActionPerformed(evt);
            }
        });

        buttonCari.setText("Cari");
        buttonCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCariActionPerformed(evt);
            }
        });

        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cariKeyPressed(evt);
            }
        });

        tbl_transaksiPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Tanggal Transaksi", "Barang", "Jumlah", "Harga"
            }
        ));
        jScrollPane2.setViewportView(tbl_transaksiPelanggan);

        jLabel1.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel1.setText("RIWAYAT TRANSAKSI PELANGGAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_dataPelanggan)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_nama_pelanggan)
                                            .addComponent(lbl_alamat_pelanggan)
                                            .addComponent(lbl_jk_pelanggan)
                                            .addComponent(lbl_noTelp_pelanggan))
                                        .addGap(49, 49, 49)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jk_laki, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(65, 65, 65)
                                                .addComponent(jk_perempuan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txt_nama_pelanggan)
                                            .addComponent(txt_notelp_pelanggan)
                                            .addComponent(txt_alamat_pelanggan)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(buttonSimpan)
                                                .addGap(18, 18, 18)
                                                .addComponent(buttonUbah)
                                                .addGap(18, 18, 18)
                                                .addComponent(buttonHapus)
                                                .addGap(18, 18, 18)
                                                .addComponent(buttonBatal)))))
                                .addGap(83, 83, 83)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonCari))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(74, 74, 74))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_dataPelanggan)
                    .addComponent(buttonCari)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nama_pelanggan)
                            .addComponent(txt_nama_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_jk_pelanggan)
                            .addComponent(jk_laki)
                            .addComponent(jk_perempuan))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_noTelp_pelanggan)
                            .addComponent(txt_notelp_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_alamat_pelanggan)
                            .addComponent(txt_alamat_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonBatal)
                            .addComponent(buttonHapus)
                            .addComponent(buttonUbah)
                            .addComponent(buttonSimpan)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCariActionPerformed
        // TODO add your handling code here:
        datatable();
    }//GEN-LAST:event_buttonCariActionPerformed

    private void buttonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBatalActionPerformed
        // TODO add your handling code here:
        kosong();
        datatable();
    }//GEN-LAST:event_buttonBatalActionPerformed

    private void buttonUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUbahActionPerformed
        // TODO add your handling code here:
        String jenis = null; //deklarasi untuk radio button terlebih dahulu
        if(jk_laki.isSelected()) {
            jenis = "Laki-laki";
        } else if(jk_perempuan.isSelected()) {
            jenis = "Perempuan";
        }
        try{
            String sql = "UPDATE pelanggan SET nama_pelanggan=?, jk_pelanggan=?, noTelp_pelanggan=?, alamat_pelanggan=? WHERE id_pelanggan=(SELECT MAX(id_pelanggan) FROM pelanggan)";
            PreparedStatement stat = connect.prepareStatement(sql); //mengkoneksikan ke sql
            stat.setString(1, txt_nama_pelanggan.getText());
            stat.setString(2, jenis);
            stat.setString(3, txt_notelp_pelanggan.getText());
            stat.setString(4, txt_alamat_pelanggan.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah"); // try catch untuk penanganan error
            kosong();
            txt_nama_pelanggan.requestFocus();
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah" + e);
        }
        datatable();
    }//GEN-LAST:event_buttonUbahActionPerformed

    private void buttonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSimpanActionPerformed
        // TODO add your handling code here:
        String jenis = null; //deklarasi untuk radio button terlebih dahulu
        if(jk_laki.isSelected()) {
            jenis = "Laki-laki";
        } else if(jk_perempuan.isSelected()) {
            jenis = "Perempuan";
        }
        String sql = "INSERT INTO pelanggan (nama_pelanggan, jk_pelanggan, noTelp_pelanggan, alamat_pelanggan) VALUES (?, ?, ?, ?)"; // jumlah (?) sesuai dengan field yang kita punya
        try{
            PreparedStatement stat = connect.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS); //mengkoneksikan ke sql
            stat.setString(1, txt_nama_pelanggan.getText()); // menaruh record ke database
            stat.setString(2, jenis);
            stat.setString(3, txt_notelp_pelanggan.getText());
            stat.setString(4, txt_alamat_pelanggan.getText());

            stat.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan"); // try catch untuk penanganan error
            kosong();
            txt_nama_pelanggan.requestFocus();
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan" + e);
        }
        datatable();
    }//GEN-LAST:event_buttonSimpanActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "hapus", "konfirmasi dialog", JOptionPane.YES_NO_OPTION); //konfirmasi apakah data benar akan dihapus sebagai tambahan keamanan
        if(ok == 0) {
            String sql = "DELETE FROM pelanggan WHERE id_pelanggan=(SELECT MAX(id_pelanggan) FROM pelanggan)";
            try {
                PreparedStatement stat = connect.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                kosong();
                txt_nama_pelanggan.requestFocus();
            }
            catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus" + e);
            }
            datatable();
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void tbl_pelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pelangganMouseClicked
        // TODO add your handling code here:
        int bar = tbl_pelanggan.getSelectedRow();

        String a = tbl_pelanggan.getValueAt(bar, 0).toString();
        String b = tbl_pelanggan.getValueAt(bar, 1).toString();
        String c = tbl_pelanggan.getValueAt(bar, 2).toString();
        String d = tbl_pelanggan.getValueAt(bar, 3).toString();
        String e = tbl_pelanggan.getValueAt(bar, 4).toString();

        
        txt_nama_pelanggan.setText(b);
        if("laki-laki".equals(c)) {
            jk_laki.setSelected(true);
        } else {
            jk_perempuan.setSelected(true);
        }
        txt_notelp_pelanggan.setText(d);
        txt_alamat_pelanggan.setText(e);
        
        datatableriwayat(a);
    }//GEN-LAST:event_tbl_pelangganMouseClicked

    private void txt_cariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            datatable();
        }
    }//GEN-LAST:event_txt_cariKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framePelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBatal;
    private javax.swing.JButton buttonCari;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton jk_laki;
    private javax.swing.JRadioButton jk_perempuan;
    private javax.swing.JLabel lbl_alamat_pelanggan;
    private javax.swing.JLabel lbl_dataPelanggan;
    private javax.swing.JLabel lbl_jk_pelanggan;
    private javax.swing.JLabel lbl_nama_pelanggan;
    private javax.swing.JLabel lbl_noTelp_pelanggan;
    private javax.swing.JTable tbl_pelanggan;
    private javax.swing.JTable tbl_transaksiPelanggan;
    private javax.swing.JTextField txt_alamat_pelanggan;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_nama_pelanggan;
    private javax.swing.JTextField txt_notelp_pelanggan;
    // End of variables declaration//GEN-END:variables

}
